### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_dask'

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cmip6-examples#1]
Both notebooks in this repo currently fail on binder: 

![image](https://user-images.githubusercontent.com/2443309/57034412-484a2b00-6c04-11e9-9489-4f0d8d05a28b.png)

It looks like the catalog has been reworked but its not clear to me how to adjust the notebooks. 

@naomi-henderson and/or @rabernat - any ideas?

**Comment by naomi-henderson** [comment]
@jhamman , yes, the cmip6 catalog was reorganized.  The datasets are now given by:
```
A3hr_cat = master_cat.cmip6.A3hr.get()
list(A3hr_cat)
```
so that:
```
ds_pr = A3hr_cat['IPSL_CM6A_LR.historical.r1i1p1f1.pr'].to_dask()
ds_tas = A3hr_cat['IPSL_CM6A_LR.historical.r1i1p1f1.tas'].to_dask()
```

**Comment by naomi-henderson** [comment]
and for the other notebook:
```
A3hr_cat = master_cat.cmip6.A3hr.get()
ds = A3hr_cat['GISS_E2_1_G.historical.r1i1p1f1.pr'].to_dask()
```

**Comment by jhamman** [comment]
okay, fixed in https://github.com/pangeo-data/pangeo_cmip6_examples/pull/2
