### ISSUE TITLE
not using local dask config

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cmip6-examples#3]
I don't think this repo is using its `.dask/config.yaml`, instead its defaulting to the dask configs from pangeo-stacks. It would be great if someone could update this binder setup to use the local dask config so we can force dask pods onto the worker-pool. We should also add: 

```
      nodeSelector:
        dask-worker: True
```

to the dask-kubernetes template, like we do here: https://github.com/pangeo-data/pangeo-example-notebooks/blob/febe8ff2609d0284708115b0a589935d63d919c3/.dask/config.yaml#L21-L22

**Comment by jhamman** [comment]
closed in 659fd959317bf72ef969a4b84a9a5d87b33d328d

**Comment by rabernat** [comment]
Thanks Joe!
