### ISSUE TITLE
 link for Tier 4 experiments points to Tier 1

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cmip6-examples#9]
Looking at CMIP6 on Google for the first time, and trying to figure out what all is here.   

On this page: https://docs.google.com/document/d/1yUx6jr9EdedCOLd--CPdTfGDwEwzPpCF6p1jRmqx-0Q/edit the link to the Tier 4 experiments doc points to the Tier 1 experiments doc.  

What is the correct link to the Tier 4 experiments doc? 

(Also, is this still the best repo to use for starting to explore CMIP6 on Google or has it been superseded?)

@naomi-henderson I see your name in the google doc, perhaps you can help?

**Comment by rabernat** [comment]
Hi Rich! Naomi has retired and that doc is old.

All of the cloud CMIP6 data are now documented here - https://pangeo-data.github.io/pangeo-cmip6-cloud/

Instructions for how to search for data are here - https://pangeo-data.github.io/pangeo-cmip6-cloud/accessing_data.html

**Comment by rsignell-usgs** [comment]
Thanks @rabernat !
